version: '3.9'

services:
  app:
    build:
      context: ./django/
    command:
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000 &&
            python manage.py runworkers"
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./django/app:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NW_CLUB_ID=${NW_CLUB_ID}
      - NW_USER_ID=${NW_USER_ID}
      - NW_EMPLOYE_ID=${NW_EMPLOYE_ID}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}

  curl-loop:
    build: ./curl-loop/
    environment:
      - TZ=Europe/Stockholm
    depends_on: 
      - app
  