services:
  app:
    build:
      context: ./django/
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./django/app:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - NW_CLUB_ID=${NW_CLUB_ID}
      - NW_USER_ID=${NW_USER_ID}
      - NW_EMPLOYE_ID=${NW_EMPLOYE_ID}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TZ=Europe/Stockholm
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  curl-loop:
    build: ./infinite-loop/
    command:
      sh -c "python loop.py"
    environment:
      - TZ=Europe/Stockholm
    depends_on: 
      - app