# Generated by Django 4.0.1 on 2022-01-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookingid', models.IntegerField(null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('dropin', models.IntegerField()),
                ('dropsamount', models.IntegerField()),
                ('endtime', models.DateTimeField()),
                ('freeslots', models.BigIntegerField()),
                ('instructor', models.CharField(max_length=100)),
                ('instructorid', models.IntegerField()),
                ('imageurl', models.CharField(blank=True, max_length=1024, null=True)),
                ('location', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=100)),
                ('scheduled', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('starttime', models.DateTimeField()),
                ('starttimestr', models.CharField(max_length=50)),
            ],
        ),
    ]
