# Generated by Django 4.0.1 on 2022-01-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nordicwellness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='scheduled',
            new_name='scheduledbooking',
        ),
    ]
