# Generated by Django 4.0.1 on 2022-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordicwellness', '0002_rename_scheduled_activity_scheduledbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bookingstartsat',
            field=models.DateTimeField(null=True),
        ),
    ]
