# Generated by Django 4.0.1 on 2022-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordicwellness', '0003_activity_bookingstartsat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bookingstartatstr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
