# Generated by Django 4.0.1 on 2022-01-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nordicwellness', '0005_remove_activity_starttimestr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='color',
        ),
    ]
